
0
Traceback (most recent call last):
  File "C:\Users\tripats\Documents\GitHub\uav_nw_madql_connectivity_pytorch\main.py", line 303, in <module>
    temp_data = u_env.step(drone_act_list, args.info_exchange_lvl)
  File "C:\Users\tripats\Documents\GitHub\uav_nw_madql_connectivity_pytorch\uav_env.py", line 242, in step
    self.state[:, 3] = sum_user_assoc / self.NUM_USER
IndexError: index 3 is out of bounds for axis 1 with size 3